name: PR Action React Frontend

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1
      - name: Install npm dependency
        run: npm install
        working-directory: './'
      # - name: Install jest
      #   run: npm i -g jest
      #   working-directory: './'
      # - name: Run tests
      #   run: npm test
      #   working-directory: './'
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}